### ISSUE TITLE
Unrecognized option 'nr'.

### ISSUE THREAD

**Issue by Lune6** [xufuji456/FFmpegAndroid#245]
Demo中点击视频降噪，没有生成视频，进度回调也没走，控制台日志如下

我看到比较明显的几行日志是

> 2024-05-29 16:55:37.662  3262-4335  FFmpegCmd               com.frank.ffmpeg                     E  Unrecognized option 'nr'.
2024-05-29 16:55:37.662  3262-4335  FFmpegCmd               com.frank.ffmpeg                     E  from native msg=Unrecognized option 'nr'.
2024-05-29 16:55:37.662  3262-4335  FFmpegCmd               com.frank.ffmpeg                     I  FFmpeg result=1
2024-05-29 16:55:37.662  3262-4335  FFmpegCmd               com.frank.ffmpeg                     E  onProgress position=100--duration=100--state=3

下面是完整日志
> 2024-05-29 16:55:37.635  3262-5885  VRI[VideoH...eActivity] com.frank.ffmpeg                     D  dispatchAppVisibility visible:true
2024-05-29 16:55:37.639  3177-3372  OplusThermalStats       system_server                        E  Error getting package info: com.frank.ffmpeg
2024-05-29 16:55:37.648  3262-3262  VRI[VideoH...eActivity] com.frank.ffmpeg                     D  setWindowStopped stopped:false
2024-05-29 16:55:37.659  3262-3262  BaseActivity            com.frank.ffmpeg                     I  filePath=/storage/emulated/0/DCIM/Camera/VID20240529122202.mp4
2024-05-29 16:55:37.661  3262-4335  FFmpegHandler           com.frank.ffmpeg                     I  handle onBegin...
2024-05-29 16:55:37.661  3262-4335  FFmpegCmd               com.frank.ffmpeg                     I  ffmpeg version 6.0
2024-05-29 16:55:37.661  3262-4335  FFmpegCmd               com.frank.ffmpeg                     I   Copyright (c) 2000-2023 the FFmpeg developers
2024-05-29 16:55:37.661  3262-4335  FFmpegCmd               com.frank.ffmpeg                     I  
2024-05-29 16:55:37.661  3262-4335  FFmpegCmd               com.frank.ffmpeg                     I    built with Android (5900059 based on r365631c) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 207d7abc1a2abf3ef8d4301736d6a7ebc224a290) (based on LLVM 9.0.8svn)
2024-05-29 16:55:37.661  3262-4335  FFmpegCmd               com.frank.ffmpeg                     I    configuration: --target-os=android --prefix=ffmpeg-android/arm64-v8a --cross-prefix=/Users/xufulong/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android- --enable-cross-compile --arch=aarch64 --cpu=armv8-a --cc=/Users/xufulong/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang --cxx=/Users/xufulong/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang++ --nm=/Users/xufulong/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-nm --strip=/Users/xufulong/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-strip --enable-cross-compile --sysroot=/Users/xufulong/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot --enable-hwaccels --enable-static --disable-shared --disable-doc --enable-neon --enable-asm --disable-small --enable-jni --disable-ffmpeg --disabl
2024-05-29 16:55:37.661  3262-4335  FFmpegCmd               com.frank.ffmpeg                     I    libavutil      58.  2.100 / 58.  2.100
2024-05-29 16:55:37.661  3262-4335  FFmpegCmd               com.frank.ffmpeg                     I    libavcodec     60.  3.100 / 60.  3.100
2024-05-29 16:55:37.661  3262-4335  FFmpegCmd               com.frank.ffmpeg                     I    libavformat    60.  3.100 / 60.  3.100
2024-05-29 16:55:37.661  3262-4335  FFmpegCmd               com.frank.ffmpeg                     I    libavfilter     9.  3.100 /  9.  3.100
2024-05-29 16:55:37.661  3262-4335  FFmpegCmd               com.frank.ffmpeg                     I    libswscale      7.  1.100 /  7.  1.100
2024-05-29 16:55:37.661  3262-4335  FFmpegCmd               com.frank.ffmpeg                     I    libswresample   4. 10.100 /  4. 10.100
2024-05-29 16:55:37.662  3262-3262  ScrollOpti...neManager] com.frank.ffmpeg                     D  updateCurrentActivity: mCurrentActivityName=com.frank.ffmpeg.activity.VideoHandleActivity, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
2024-05-29 16:55:37.662  3262-3262  ActivityThread          com.frank.ffmpeg                     D  ComponentInfo{com.frank.ffmpeg/com.frank.ffmpeg.activity.VideoHandleActivity} checkFinished=false 2
2024-05-29 16:55:37.662  3262-4335  FFmpegCmd               com.frank.ffmpeg                     E  Unrecognized option 'nr'.
2024-05-29 16:55:37.662  3262-4335  FFmpegCmd               com.frank.ffmpeg                     E  from native msg=Unrecognized option 'nr'.
2024-05-29 16:55:37.662  3262-4335  FFmpegCmd               com.frank.ffmpeg                     I  FFmpeg result=1
2024-05-29 16:55:37.662  3262-4335  FFmpegCmd               com.frank.ffmpeg                     E  onProgress position=100--duration=100--state=3
2024-05-29 16:55:37.662  3262-4335  FFmpegHandler           com.frank.ffmpeg                     I  handle onEnd time=0.1
2024-05-29 16:55:37.662  3262-3262  ResourcesManagerExtImpl com.frank.ffmpeg                     D  applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
2024-05-29 16:55:37.663  3262-3262  Quality                 com.frank.ffmpeg                     I  Skipped: false 0 cost 1.831458 refreshRate 8333333 bit true processName com.frank.ffmpeg
2024-05-29 16:55:37.666  3262-3262  ViewRootImplExtImpl     com.frank.ffmpeg                     D  wrapConfigInfoIntoFlags rotation=0, smallestScreenWidthDp=360, relayoutAsync=false, newFlags=23592960, title=com.frank.ffmpeg/com.frank.ffmpeg.activity.VideoHandleActivity
2024-05-29 16:55:37.685  3262-3262  VRI[VideoH...eActivity] com.frank.ffmpeg                     D  relayoutWindow result, sizeChanged:false, surfaceControlChanged:true, transformHintChanged:false, mSurfaceSize:Point(1080, 2376), mLastSurfaceSize:Point(1080, 2376), mWidth:1080, mHeight:2376, requestedWidth:1080, requestedHeight:2376, transformHint:0, lastTransformHint:0, installOrientation:0, displayRotation:0, isSurfaceValid:true, attr.flag:-2122252032, useBlast:true, tmpFrames:ClientWindowFrames{frame=[0,0][1080,2376] display=[0,0][1080,2376] parentFrame=[0,0][0,0]}, params:{(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x10302fe
                                                                                                      fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
                                                                                                      pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST FIT_INSETS_CONTROLLED
                                                                                                      bhv=DEFAULT
                                                                                                      fitSides= CLP[ ]}
2024-05-29 16:55:37.686  3262-3262  VRI[VideoH...eActivity] com.frank.ffmpeg                     W  updateBlastSurfaceIfNeeded, surfaceSize:Point(1080, 2376), lastSurfaceSize:Point(1080, 2376), format:-1, blastBufferQueue:null
2024-05-29 16:55:37.686  3262-3262  BufferQueueConsumer     com.frank.ffmpeg                     D  [](id:cbe00000004,api:0,p:-1,c:3262) connect: controlledByApp=false
2024-05-29 16:55:37.687  3262-3895  BufferQueueProducer     com.frank.ffmpeg                     D  [VRI[VideoHandleActivity]#4(BLAST Consumer)4](id:cbe00000004,api:1,p:3262,c:3262) connect: api=1 producerControlledByApp=true
2024-05-29 16:55:37.687  3262-3895  OpenGLRenderer          com.frank.ffmpeg                     E  Unable to match the desired swap behavior.
2024-05-29 16:55:37.689  3262-3262  SurfaceControl          com.frank.ffmpeg                     I   setExtendedRangeBrightness sc=Surface(name=com.frank.ffmpeg/com.frank.ffmpeg.activity.VideoHandleActivity)/@0x73cb8d2,currentBufferRatio=1.0,desiredRatio=1.0
2024-05-29 16:55:37.697  3262-3895  BLASTBufferQueue        com.frank.ffmpeg                     D  [VRI[VideoHandleActivity]#4](f:0,a:1) acquireNextBufferLocked size=1080x2376 mFrameNumber=1 applyTransaction=true mTimestamp=32219956949009(auto) mPendingTransactions.size=0 graphicBufferId=14010183319571 transform=0
2024-05-29 16:55:37.697  3262-3895  VRI[VideoH...eActivity] com.frank.ffmpeg                     D  Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
2024-05-29 16:55:37.698  3262-3262  VRI[VideoH...eActivity] com.frank.ffmpeg                     D  draw finished.
2024-05-29 16:55:37.698  3262-3262  VRI[VideoH...eActivity] com.frank.ffmpeg                     D  reportDrawFinished
2024-05-29 16:55:37.698  3262-3262  ViewRootImplExtImpl     com.frank.ffmpeg                     D  setMaxDequeuedBufferCount: 2
2024-05-29 16:55:37.699  3262-3262  ViewRootImplExtImpl     com.frank.ffmpeg                     D  onDisplayChanged 0 for VRI android.view.ViewRootImpl@c2232fd
2024-05-29 16:55:37.700  3262-3262  ViewRootImplExtImpl     com.frank.ffmpeg                     D  onDisplayChanged 0 for VRI android.view.ViewRootImpl@9451a6c
2024-05-29 16:55:41.925  3262-3262  ANR_LOG                 com.frank.ffmpeg                     E  Entry{target='com.frank.ffmpeg.activity.VideoHandleActivity$mHandler$1', callback='', messageName='com.frank.ffmpeg.activity.VideoHandleActivity$mHandler$1', wall=4224', mWhen=32219921, mArg1=0, mArg2=0, mWhat=9012, mCount=0
2024-05-29 16:55:41.925  3262-6405  Quality                 com.frank.ffmpeg                     I  stackInfo :----- pid 3262 at 2024-05-29 16:55:41.906 -----;Cmd line: com.frank.ffmpeg;"main" prio=5 tid=2 RUNNABLE sysTid=3262;  at android.graphics.drawable.Drawable.getBounds(Drawable.java:316);  at android.graphics.drawable.GradientDrawable.getOutline(GradientDrawable.java:1970);  at android.graphics.drawable.DrawableContainer.getOutline(DrawableContainer.java:138);  at android.view.ViewOutlineProvider$1.getOutline(ViewOutlineProvider.java:38);  at android.view.View.rebuildOutline(View.java:19472);  at android.view.View.invalidateDrawable(View.java:25084);  at android.widget.TextView.invalidateDrawable(TextView.java:8706);  at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:474);  at android.graphics.drawable.Drawable.setVisible(Drawable.java:921);  at android.graphics.drawable.DrawableContainer.setVisible(DrawableContainer.java:420);  at android.view.View.onVisibilityAggregated(View.java:16272);  at android.widget.TextView.onVisibilityAggregated(TextView.java:12779);  at android.view.View.dispatchVisibilityAggregated(View.java:16248);  at android.view.ViewGroup.dispatchVisibilityAggregated(ViewGroup.java:1661);  at android.view.ViewGroup.dispatchVisibilityAggregated(ViewGroup.java:1661);  at android.view.View.setFlags(View.java:17774);  at android.view.View.setVisibility(View.java:12968);  at com.frank.ffmpeg.activity.VideoHandleActivity$mHandler$1.handleMessage(VideoHandleActivity.kt:68);  at android.os.Handler.dispatchMessage(Handler.java:106);  at android.os.Looper.loopOnce(Looper.java:257);  at android.os.Looper.loop(Looper.java:368);  at android.app.ActivityThread.main(ActivityThread.java:8848);  at java.lang.reflect.Method.invoke(Native Method);  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572);  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049);
2024-05-29 16:55:41.926  3262-3262  VRI[VideoH...eActivity] com.frank.ffmpeg                     D  onFocusEvent true
2024-05-29 16:55:41.928  3262-3382  Quality                 com.frank.ffmpeg                     I  Blocked msg = Package name: com.frank.ffmpeg [ schedGroup: 5 schedPolicy: 0 ] process the message: { when=-4s264ms what=9012 target=com.frank.ffmpeg.activity.VideoHandleActivity$mHandler$1 } took 4225 ms
2024-05-29 16:55:43.402  3262-3382  Quality                 com.frank.ffmpeg                     I  Blocked msg = Package name: com.frank.ffmpeg [ schedGroup: 5 schedPolicy: 0 ] process the message: { when=-5s736ms what=1112 target=com.frank.ffmpeg.activity.VideoHandleActivity$mHandler$1 } took 1471 ms
2024-05-29 16:55:43.402  3262-3262  Choreographer           com.frank.ffmpeg                     I  Skipped 689 frames!  The application may be doing too much work on its main thread.
2024-05-29 16:55:43.403  3262-3262  Quality                 com.frank.ffmpeg                     I  Skipped: false 689 cost 5707.2603 refreshRate 8280776 bit true processName com.frank.ffmpeg
2024-05-29 16:55:43.441  3262-3262  ViewRootImplExtImpl     com.frank.ffmpeg                     D  onDisplayChanged 0 for VRI android.view.ViewRootImpl@c2232fd
2024-05-29 16:55:43.442  3262-3262  ViewRootImplExtImpl     com.frank.ffmpeg                     D  onDisplayChanged 0 for VRI android.view.ViewRootImpl@9451a6c
2024-05-29 16:55:43.443  3262-3262  VRI[VideoH...eActivity] com.frank.ffmpeg                     W  handleResized abandoned!
2024-05-29 16:55:43.457  3262-3334  OpenGLRenderer          com.frank.ffmpeg                     I  Davey! duration=5754ms; Flags=0, FrameTimelineVsyncId=15383721, IntendedVsync=32219955293667, Vsync=32225660748331, InputEventId=0, HandleInputStart=32225666883278, AnimationStart=32225666891872, PerformTraversalsStart=32225666895882, DrawStart=32225691003590, FrameDeadline=32219977821330, FrameInterval=32225662554059, FrameStartTime=8280776, SyncQueued=32225697529372, SyncStart=32225697695570, IssueDrawCommandsStart=32225697973851, SwapBuffers=32225699995465, FrameCompleted=32225710134945, DequeueBufferDuration=30104, QueueBufferDuration=533125, GpuCompleted=32225710134945, SwapBuffersCompleted=32225701047497, DisplayPresentTime=0, CommandSubmissionCompleted=32225699995465, 
2024-05-29 16:55:44.451  3262-3998  OplusScrollToTopManager com.frank.ffmpeg                     D  com.frank.ffmpeg/com.frank.ffmpeg.activity.VideoHandleActivity,This DecorView@4515d79[VideoHandleActivity] change focus to true
2024-05-29 16:56:02.684  3262-3262  Compatibil...geReporter com.frank.ffmpeg                     D  Compat change id reported: 171228096; UID 10327; state: ENABLED
2024-05-29 16:56:02.774  3262-3262  ViewRootImplExtImpl     com.frank.ffmpeg                     D  MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=985.3633, y[0]=244.77637, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=32245025, downTime=32244774, deviceId=6, source=0x1002, displayId=0, eventId=877676338 } handled by client, just return

**Comment by xufuji456** [comment]
感谢指出问题，已修正
